server:
 port: 8080
spring:
 config:
   import:
    - optional:configserver:http://localhost:8088/
 profiles:
    active:
    - qa
 application:
    name: gateway
 cloud:
    
    ### QUESTA E' LA PARTE DEL GATEWAY ###
    ### QUI AD ES. SPECIFICHIAMO QUALI SONO GLI URL DEI SERVIZI VERSO ###
    ### CUI INSTRADARE LE RICHIESTE FATTE TRAMITE IL GATEWAY ###
    
    gateway:
      routes:
      #for book service
      - id: book-service
        uri: lb://book-service
        predicates:
         - Path=/book-service/**
        filters:
         - StripPrefix=1
      #for rating service
      - id: rating-service
        uri: lb://rating-service
        predicates:
         - Path=/rating-service/**
        filters:
         - StripPrefix=1
eureka:
  client:
    
    ### DOVE VIENE REGISTRATO QUESTO SERVIZIO? ###
    
    service-url:
      default-zone: http://localhost:8761/eureka